build: put all artifacts into one directory

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,6 +8,16 @@ on:
 jobs:
   build-windows:
     runs-on: windows-latest
+    env:
+      RUNNER_PATH: build/windows/x64/runner
+      ARTIFACT_PATH: ${{ env.RUNNER_PATH }}/Artifacts
+      BUILD_DIR_PATH: ${{ env.RUNNER_PATH }}/Release/
+      ARCHIVE_NAME: AndroidSideloader-${{ github.ref_name }}-Windows-Portable.zip
+      ARCHIVE_PATH: ${{ env.ARTIFACT_PATH }}/${{ env.ARCHIVE_NAME }}
+      INSTALLER_NAME: AndroidSideloader-${{ github.ref_name }}-Windows-Installer.exe
+      INSTALLER_PATH: ${{ env.ARTIFACT_PATH }}/${{ env.INSTALLER_NAME }}
+      PACKAGE_NAME: AndroidSideloader-${{ github.ref_name }}.exe
+      PACKAGE_PATH: ${{ env.ARTIFACT_PATH }}/AndroidSideloader-${{ github.ref_name }}.exe
     permissions:
       contents: write
     name: Build Flutter App Windows
@@ -15,30 +25,13 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Define Artifact Paths
-        id: define-artifact-paths
-        run: |
-          $runner="build/windows/x64/runner"
-          $build="$runner/Release/"
-          $archiveName="AndroidSideloader-${{ github.ref_name }}-Windows-Portable.zip"
-          $archive="$runner/$archiveName"
-          $installerName="AndroidSideloader-${{ github.ref_name }}-Windows-Installer.exe"
-          $installer="$runner/Installer/$installerName"
-          $packageName="AndroidSideloader-${{ github.ref_name }}.exe"
-          echo "BUILD_DIR_PATH=$build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "ARCHIVE_NAME=$archiveName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "ARCHIVE_PATH=$archive" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "INSTALLER_NAME=$installerName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "INSTALLER_PATH=$installer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "PACKAGE_NAME=packageName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-
       - name: Extract Release Notes
         id: extract_changelog
         run: |
           $ReleaseNotes = & "scripts/get-release-notes.ps1" -VersionName ${{ github.ref_name }}
-          if ($LASTEXITCODE -ne 0) {
-            Write-Output "$ReleaseNotes"
-            exit 1
+          if ($LASTEXITCODE -ne 0 -or -not (Test-Path ./ReleaseNotes.md)) {
+              Write-Error "Failed to create ReleaseNotes.md"
+              exit 1
           }
           $ReleaseNotes | Out-File -FilePath "./ReleaseNotes.md" -Encoding utf8
 
@@ -70,7 +63,7 @@ jobs:
 
       - name: Create enigma package
         run: |
-          & '${{ env.ENIGMA }}' .\package.evb -output ${{ env.PACKAGE_NAME }}
+          & '${{ env.ENIGMA }}' .\package.evb -output ".\${{ env.PACKAGE_PATH }}"
 
       - name: Compress Build Directory
         run: |
